#!/usr/bin/env python3
from os import environ
import subprocess
import sys

if environ.get('SKIP_HAIKU_HOOKS', '0') == '1':
  # We have been expliticly asked to do nothing.
  sys.exit(0)

print('Syncing dependencies....')
subprocess.call(['yarn', 'install'])
